# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

format = """
[](fg:zinc800)\
$os\
$username\
[](fg:zinc800 bg:zinc300)\
$directory\
[](fg:zinc300 bg:zinc100)\
$git_branch\
$git_status\
$git_metrics\
[](fg:zinc100 bg:zinc700)\
$rust\
$nodejs\
[](fg:zinc700 bg:zinc800)\
$cmd_duration\
[](fg:zinc800)\
$line_break\
$character"""

# Disable the blank line at the start of the prompt
add_newline = false

palette = "tailwind"

# Tailwind 4.0 color palette
[palettes.tailwind]
white = "#ffffff"

red600 = "#dc2626"

lime700 = "#4d7c0f"

pink500 = "#ec4899"

zinc100 = "#f4f4f5"
zinc300 = "#d4d4d8"
zinc600 = "#525252"
zinc700 = "#3f3f46"
zinc800 = "#27272a"
zinc900 = "#18181b"

[character]
success_symbol = "[❯](bold zinc100)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[os]
disabled = false
format = "[$symbol]($style)"
style = "bg:zinc800 fg:zinc300"

[os.symbols]
Ubuntu = "󰕈"
Linux = ""
Macos = ""
Windows = ""

[username]
show_always = true
format = "[ $user ]($style)"
style_user = "bg:zinc800 fg:zinc100"
style_root = "bg:zinc800 fg:zinc100"

[directory]
format = "[ $path ]($style)"
style = "bg:zinc300 fg:zinc900"
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
symbol = ""
format = "[ $symbol $branch]($style)"
style = "bg:zinc100 fg:zinc900"

[git_status]
format = "[(*$conflicted$untracked$modified$staged$renamed$deleted) ]($style)"
style = "bg:zinc100 fg:pink500"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"

[git_metrics]
disabled = false
format = "([+$added ]($added_style))([-$deleted ]($deleted_style))"
added_style = "bg:zinc100 fg:lime700"
deleted_style = "bg:zinc100 fg:red600"

[rust]
symbol = ""
format = "[ $symbol ($version) ]($style)"
style = "bg:zinc700 fg:zinc300"

[nodejs]
symbol = ""
format = "[ $symbol ($version) ]($style)"
style = "bg:zinc700 fg:zinc300"

[cmd_duration]
min_time = 0
format = "[ 󰔛 $duration]($style)"
style = "bg:zinc800 fg:zinc300"
