# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

right_format = """$cmd_duration"""

# Disable the blank line at the start of the prompt
add_newline = false

palette = "tailwind"

# Tailwind 4.0 color palette
[palettes.tailwind]
teal600 = "#009689" # oklch(0.6 0.118 184.704)
teal950 = "#022f2e" # oklch(0.277 0.046 192.524)

pink300 = "#fda5d5" # oklch(0.823 0.12 346.018)

zinc800 = "#27272a" # oklch(0.274 0.006 286.033)

[character]
success_symbol = "[](bold purple)"
error_symbol = "[](bold red)"
vimcmd_symbol = "[](bold green)"

[directory]
format = """
[](teal600)\
[󰉋](bg:teal600 fg:teal950)\
[ ](fg:teal600 bg:zinc800)\
[$path](bg:zinc800 bold)\
[ ](zinc800)"""
truncate_to_repo = false

[git_branch]
format = """
[](teal600)\
[ ](bg:teal600 fg:teal950)\
[ ](fg:teal600 bg:zinc800)\
[$branch](bg:zinc800 bold)"""

[git_status]
format = """
[(*$conflicted$untracked$modified$staged$renamed$deleted)](bg:zinc800 fg:pink300)\
[ ](zinc800)"""
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"
