# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

right_format = """$cmd_duration"""

# Disable the blank line at the start of the prompt
add_newline = false

palette = "tailwind"

[palettes.tailwind]
teal500 = "#14b8a6"
teal900 = "#134e4a"

pink300 = "#fda5d5"

zinc800 = "#27272a"

[character]
success_symbol = "[](bold purple)"
error_symbol = "[](bold red)"
vimcmd_symbol = "[](bold green)"

[directory]
format = """
[](teal500)\
[󰉋](bg:teal500 fg:teal900)\
[](fg:teal500 bg:zinc800)\
[ $path](bg:zinc800 bold)\
[ ](zinc800)"""
truncate_to_repo = false

[git_branch]
format = """
[](teal500)\
[ ](bg:teal500 fg:teal900)\
[](fg:teal500 bg:zinc800)\
[ $branch](bg:zinc800 bold)"""

[git_status]
format = """
[(*$conflicted$untracked$modified$staged$renamed$deleted)](bg:zinc800 fg:pink300)\
[ ](zinc800)"""
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"
